version: "3"
services:
  app:
    image: node:18.16.1-alpine
    container_name: ulab_front
    tty: true
    working_dir: /app
    ports:
      - "3001:3001" # 開発用
      - "4000:4000" # 本番用
    volumes:
      - .:/app/
    command: yarn dev -p 3001
